---
sudo: required

# env:
#   global:
#   - VAGRANT_VERSION="2.2.9"

notifications:
  slack:
    on_failure: always

matrix:
  fast_finish: true
  include:

    - name: "Python 3.7 on bionic amd64"
      dist: bionic
      language: python
      python: 3.7
      before_install:
        - pip3 install virtualenv
        - virtualenv -p $(which python3) ~venvpy3
        - source ~venvpy3/bin/activate
        - pip install -r requirements.txt
      script:
          - sudo make deploy-libvirt
          - sudo make deploy-vagrant
          - sudo make deploy-boxes
      after_success:
        - deactivate
